---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-dl-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtube-dl-web
  template:
    metadata:
      labels:
        app: youtube-dl-web
    spec:
      containers:
        - name: youtube-web-dl
          image: rl1987/youtube-dl-web:1.0.3
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 1
            tcpSocket:
              port: 8000
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /
              port: 8000
